name = input("이름을 입력해주세요: ")
id=input("학번을 입력해주세요: ")
major=input("학과을 입력해주세요: ")
grade=input("학년을 입력해주세요: ")
univ=input("학교를 입력해주세요: ")

print("<출력>")
print("이름 :",name)
print("학번 :",id)
print("학과 :",major)
print("학년 :",4)
print("학교 :",univ)
